services:
  - type: web
    name: lawchat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_TYPE
        value: sqlite
      - key: CORS_ORIGINS
        value: https://frontend-83k5hznuf-bora-kims-projects.vercel.app
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"

